name: handy
version: 1.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 4.0.3
  carousel_slider: 4.2.1
  http: 0.13.5
  get_storage: 2.1.1
  firebase_core: 2.10.0
  cloud_firestore: 4.5.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

flutter_icons:
  image_path: "icons/logo2.png"
  android: true
  ios: true
  remove_alpha_ios: true
  resize_behavior: shrink_only